steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "tar"
  args: ["-czf", "latest.tar.gz", "."]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "scp", "--recurse", "$BRANCH_NAME-latest.tar.gz", "instance-maintenance-test:/tmp", "--zone", "us-central1-a"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "scp", "deploy.sh", "instance-maintenance-test:/tmp", "--zone", "us-central1-a"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "ssh", "instance-maintenance-test", "--zone", "us-central1-a", "--command", "sudo sh /tmp/deploy.sh /tmp/$BRANCH_NAME-latest.tar.gz $BRANCH_NAME"]
 