# Deploy a basic flask application
# Define the three variables on the trigger : _INSTANCE_NAME, _INSTANCE_ZONE and _INSTANCE_PORT
steps:
# create the artifact in gzip format
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "tar"
  args: ["-czf", "$BRANCH_NAME-latest.tar.gz", "."]
# copy the artifact into the instance
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "scp", "--recurse", "$BRANCH_NAME-latest.tar.gz", "$_INSTANCE_NAME:/tmp", "--zone", "$_INSTANCE_ZONE"]
# copy the script of the deployement into the instance
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "scp", "deploy.sh", "$_INSTANCE_NAME:/tmp/$BRANCH_NAME-deploy.sh", "--zone", "$_INSTANCE_ZONE"]
# launch the script of the deployement from the instance
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "ssh", "$_INSTANCE_NAME", "--zone", "$_INSTANCE_ZONE", "--command", "sudo sh /tmp/$BRANCH_NAME-deploy.sh /tmp/$BRANCH_NAME-latest.tar.gz $BRANCH_NAME $_INSTANCE_PORT"]
 