steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["version"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "scp", "--recurse", "deploy.sh", "instance-maintenance-test:/tmp", "--zone", "us-central1-a"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "ssh", "instance-maintenance-test", "--zone", "us-central1-a", "--command", "/tmp/deploy.sh"]
 