steps:
- name: "gcr.io/cloud-builders/git"
  args: ["archive", "-o", "latest.zip", "HEAD"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "scp", "--recurse", "latest.zip", "instance-maintenance-test:/tmp", "--zone", "us-central1-a"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "ssh", "instance-maintenance-test", "--zone", "us-central1-a", "--command", "sudo sh /tmp/deploy.sh"]
 