steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "scp", "--recurse", "deploy.sh", "instance-maintenance-test:/tmp", "--zone", "us-central1-a"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "ssh", "--command", "'sh /tmp/deploy.sh'", "--zone", "us-central1-a"]
 